### PR TITLE
Optional http client

### PR DESCRIPTION
**Pull request by FistedByDionysus**
- add client feature and set as default
- Refactor http rpc code into client.rs
- maintain current exported symbols
- update ci and test for feature compatibility
- Fix clippy::derive-partial-eq-without-eq

Export only the JsonRPC models with:

```
# Cargo.toml
monero-rpc = { version = "..", default-features = false }
```

### CODE REVIEW

**Comment by FistedByDionysus** [comment]
An alternative to this would be breaking the models into their own crate. Similar to https://github.com/rust-bitcoin/rust-bitcoincore-rpc

**Comment by FistedByDionysus** [comment]
Also just saw the clippy issue is fixed in https://github.com/monero-ecosystem/monero-rpc-rs/pull/78

**Comment by h4sh3d** [comment]
Hello, thanks for contributing to this project!

If I get the goal of this PR right you would like to use the models in another project without importing the client and its implementation. Is that correct?

**Comment by TheCharlatan** [comment]
cACK

**Pull request closed without merging**
