### PR TITLE
RPC authentication

### PR DESCRIPTION
**Pull request by refactor-ring**
This PR implements #43 for both monerod rpc and wallet rpc 

Docker containers with --rpc-login enabled have been added for both monerod and monero-wallet-rpc, tests are included as well.

Currently I added a new constructor RpcClient::with_authentication() but seeing that both #77 and #81 are using the current RpcClient::new() in a backwards incompatible way I also made a branch with a new RpcClient builder called RpcClientBuilder which would allow for backwards compatibility and enable all three new features to be used together.

This is can be seen at https://github.com/monero-ecosystem/monero-rpc-rs/compare/master...refactor-ring:rpc-client-builder-merged?expand=1

UPDATE
Had to change the github actions setup a bit to make the tests pass with the new containers, instead of redefining the containers in the github actions config it now spins up the containers through docker-compose up using the existing docker-compose.yml

### CODE REVIEW

**Comment by silverpill** [comment]
+1 for builder

Also it would be nice to have a feature flag for this, to avoid pulling `diqwest` if you don't need it.

**Comment by TheCharlatan** [comment]
Also much in favour of using the builder pattern.

**Comment by refactor-ring** [comment]
Added a feature "rpc_authentication" however when using the  "dep:diqwest" notation in cargo.toml the tests fail because of using rust 1.56 and the "dep:" syntax only got added in rust 1.60.

Also, should I make a separate PR for the builder pattern ?

**Comment by TheCharlatan** [comment]
> Also, should I make a separate PR for the builder pattern ?

I think that would make things a bit easier to review, yes. I'll let @h4sh3d weigh in first on bumping the msrv.

**Comment by h4sh3d** [comment]
Included in #92

**Pull request closed without merging**
